#!/usr/bin/env python3

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License
# for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
from subprocess import call
import os

from source.coalaApp import coalaApp


def main():
    data_path = os.path.join(os.path.dirname(__file__), "data")
    if not os.path.exists(os.path.join(data_path, "coala.gresource")):
        print("Calling ",
              "glib-compile-resources",
              os.path.join(data_path, "coala.gresource.xml"),
              "--sourcedir="+data_path)
        call(["glib-compile-resources",
              os.path.join(data_path, "coala.gresource.xml"),
              "--sourcedir="+data_path])

    app = coalaApp(data_path)
    app.run(sys.argv)


if __name__ == "__main__":
    sys.exit(main())
